### PR TITLE
iconfix

### PR DESCRIPTION
**Pull request by andiloveher**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by amcdnl** [comment]
Can you please fill out the form?

**Comment by psreeks** [comment]
@amcdnl can you merge these changes? its hard to override the pager classes with font awesome classes.

**Comment by amcdnl** [comment]
I'll review today. I need to go through it since there are other changes here.

**Comment by psreeks** [comment]
thanks @amcdnl

**Comment by amcdnl** [comment]
@psreeks - What exactly does this PR do? Also, it looks like there is merges from other commits in here and also the built files. Can you point me to the exact change please?

**Comment by amcdnl** [comment]
Wait, this is actually achievable with the `cssClasses` input

```
  @Input() cssClasses: any = {
    sortAscending: 'icon-up',
    sortDescending: 'icon-down',
    pagerLeftArrow: 'icon-left',
    pagerRightArrow: 'icon-right',
    pagerPrevious: 'icon-prev',
    pagerNext: 'icon-skip'
  };
```

**Pull request closed without merging**
