### PR TITLE
Tree grid support added - continued

### PR DESCRIPTION
**Pull request by isaacplmann**
This is a continuation of PR #1189 .  I don't know how to make a PR to @sanbornsen 's fork - it forces me to make any PRs to the base fork.  So here are my updates - so that people can take a look.

### CODE REVIEW

**Comment by isaacplmann** [comment]
@amcdnl What can we do to get this merged?  Is there anything still missing? Is there too much functionality in one PR?

**Comment by bhuber2010** [comment]
Great work both sanbornsen and isaacplmann! This is huge for the project I am working on right now too and am using this fork/branch but would be great to be able to wrap this up and merge it in.

**Comment by isaacplmann** [comment]
Updated so that it's ready to merge.

**Comment by sanbornsen** [comment]
@isaacplmann thanks for making the changes and taking it forward. 👍 I'll be happy to see it merged.

**Comment by bhuber2010** [comment]
@isaacplmann or @sanbornsen Any ideas on getting virtual scrolling working with the tree? In setting scrollbarV=true requires the rowHeight to be set to a value (can't be auto) and that seems not to play well with the tree. I can take a look into it, but figured I'd throw it out if either of you has an idea since you built the tree functionality. My use case is I have a very large tree and the table is hidden to start, showing it then drags the browser down to render the entire tree.

**Comment by lefthand250** [comment]
Excellent work. I'll be happy to see it merged.

**Comment by Elrhino** [comment]
Awesome work guys 👍  Is there anything we can do to get this merged ASAP?

**Comment by amcdnl** [comment]
@isaacplmann can u resolve conflicts?

**Comment by isaacplmann** [comment]
Merged.  I was on vacation last week.

**Comment by nguyenkien** [comment]
Any example to use tree?

**Comment by dlorych** [comment]
PR comes with 2 demos - with data accessed locally on client, and the other one calling server to fetch data:
demo/tree/client-tree.component.ts
demo/tree/fullscreen.component.ts

**Comment by Chris-V** [comment]
I my own fork to try this feature and it's awesome. Great job!

I only have two small gripes (although not very hard to overcome):
* The tree action button. We have other buttons in our datatables, so this one was tricky to style without doing some nasty CSS selectors. It would be great to add a css class to it directly in ngx-datatable. That would make life easier ;)
* The `treeFromRelation` and `treeToRelation` attributes don't support nested properties. I copied the relation properties to my "row" interface to overcome this, but that would be great if nested properties were supported. `ngx-datatable-column`'s prop attribute supports that and it's sooo useful.

Keep up the good work, I'm eager to see that merged and stop relying on a fork :D

**Comment by isaacplmann** [comment]
Css class on the button is a good idea. What do you mean by nested
properties?

**Comment by Chris-V** [comment]
Suppose I have a structure like so:
```typescript
interface EmployeeRow {
    employee: {
        id: string;
        managerId: string;
        name: string;
    };
    treeStatus: TreeStatus;
}
```

And a table similar to this:
```html
<ngx-datatable
  [rows]="..."
  treeFromRelation="employee.managerId"
  treeToRelation="employee.id">
    <ngx-datatable-column
      prop="employee.name"
      [isTreeColumn]="true"></ngx-datatable-column>
</ngx-datatable>
```

The property is read properly in the column, but not the tree relation attributes. There is a `getterForProp` function in `column-prop-getters.ts`, that I believe is used to achieve this result.

**Comment by isaacplmann** [comment]
@Chris-V I added the getterForProp and button class that you asked for.  Also up to date with master.

**Comment by isaacplmann** [comment]
Don't merge this just yet, I want to switch from using a `treeIconTemplate` to a `treeButtonTemplate` so that you have full control over what you want to use for the tree toggler.  I plan to have a new commit ready in the morning.

**Comment by isaacplmann** [comment]
@Chris-V can you take a look at the new `treeToggleTemplate`?  It's used in the full screen tree demo.  I think this will be cleaner than trying to modify the toggle with css.

**Comment by isaacplmann** [comment]
I'm happy with the PR now and would be glad to see it merged.

**Comment by igortg** [comment]
Hey guys. This would be an awesome feature. Any news on merging that?

**Comment by Snap252** [comment]
Any news here?

**Comment by reisang** [comment]
@isaacplmann can we see this merge through, would really appreciate it.

**Comment by isaacplmann** [comment]
I'd love for it to be merged. I can't control that.

**Comment by isaacplmann** [comment]
Merged and release folder has been reverted to the current master version.

**Comment by marjan-georgiev** [comment]
LGTM, @sanbornsen and @isaacplmann thank you for the contribution!

**Comment by Snap252** [comment]
Will it be possible to create the subtrees dynamically on opening it?
Would be a great performance gain.

**Comment by isaacplmann** [comment]
@Snap252 I'm not sure what you're asking for.  Could you explain a bit more?  Maybe a little code snippet would help.

**Comment by zd5043039119** [comment]
Is this feature completed? I don't find how to expand or collapse the tree node row

**Comment by Snap252** [comment]
@isaacplmann :
its about opening a level. When you do, can the data be collected from the server for the opened node?

**Comment by melisa29** [comment]
Is there any documentation for the tree grid? Thanks!

**Comment by prashantst1992** [comment]
@isaacplmann  Please provide some link to the documentation of the tree grid. Thanks!

**Pull request merged**
