### PR TITLE
Improve virtualization as a flag. The original idea is be able to configure paging and scrolling without virtualization 

### PR DESCRIPTION
**Pull request by lneninger**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
The vertical scroll feature [scrollbarV]="true" is assuming  that virtualization is active. So, when is desired to have external pagination with scrolling and no virtualization the table mechanism try the scrolling as a paging event and force the current page.

**What is the new behavior?**
With external pagination and scrollbarV and no virtualization the data-table mechanism trigger the paging event on event  onFooterPage only avoiding the undesired behavior of auto paging back to first page after select a page on the pagination component; which is the desired behavior. The original behavior for scrollbarV with virtualization remains the same as well as paging without scrolling.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by lgoudriaan** [comment]
@amcdnl Can you take a look at this? This will fix: #816,#349 and #1126,

**Comment by osnoser1** [comment]
Hello, I have several months working with these changes and they are working correctly, you could have an eye here, please? 😪

**Comment by BitSchupser** [comment]
Works like a charm, please merge this PR. I need this feature and currently I am forced to work with a fork to have this feature (see https://github.com/XITASO/ngx-datatable/tree/merge_pr_1297)

**Comment by house-md** [comment]
Hello, please is it possible to have this PR merged in near future? Thank you

**Comment by marjan-georgiev** [comment]
Looks good. Thank you @lneninger 👍

**Comment by isostarec** [comment]
IMO `[virtualization]` should be `false` by default. I integrated standard pagination and lost a few hours on wondering why does it change pages suddenly. Also, I don't have `[scrollbarV]` active. Is there a reason `[virtualization]` isn't `false` by default?

**Pull request merged**
