### PR TITLE
(feature) Add an option to only use pager when using scrollbarv and external pager

### PR DESCRIPTION
**Pull request by vixriihi**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Page change event is triggered from the footer and when scrolling content

**What is the new behavior?**
You can use onlyPagerToChangePage to force paging events to happen only from the footer.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
This allows me to have scrollbarV and externalPager true.
Goal is to have sticky header, horzontal & vertical scroll and server-side pages.

### CODE REVIEW

**Comment by wizarrc** [comment]
@vixriihi This doesn't smell right. I'm not sure what is being achieved here.

Why not just turn off `scrollbarV`? How does not having this prevent a stick header?

**Comment by vixriihi** [comment]
Yes I wish I could find a good solution for this but... 
If I turn of scrollbarV page would have a lot of rows at same time -> very slow page

This PR allows me to have body that uses scrollbarV to only render the visible rows and to have the pager in the footer for external server-side paging

**Comment by wizarrc** [comment]
http://plnkr.co/edit/fub1CQpqxMxEuB7exDhU?p=preview has external paging turned on

You could then prefetch the nearby pages. If they jump to it, it starts out displaying blank till you get the page event, fetch the data, modify the array. I have a fork that uses a virtual scrollbar, and that allows all that to happen before it actually performs the scroll to prevent displaying whitespace.

**Comment by vixriihi** [comment]
Here is a plunker to hopefully better describe the problem http://plnkr.co/edit/XiNrMadcEzHISptcJZQt
Pages load nice and fast until you click the last page link in the footer.

**Comment by wizarrc** [comment]
@vixriihi have you tried turning off `scrollbarV` and turning on `limit`? Just get rid of the scroll bar altogether.

**Comment by vixriihi** [comment]
Yes I have. Our customer want's 5000 rows per page and without scrollbarV browsers just cannot handle it.

**Comment by wizarrc** [comment]
ah, yeah, that's a problem. I would suggest you fork it until this can be generalized. That's something I'm working on in my fork but I can't say when I might get that into the library. It was never really designed for that workflow, and only ever added external paging to try to bridge the gap.

**Comment by vixriihi** [comment]
SGTM This PR solves this problem by letting limit to define how many rows will be in the body and then by handling page change events only from the footer. ScrollbarV can easily handle 5000 rows and since there is full set of new rows when page is changed there is no problem of huge master row set with all the rows in it. Here is a plunker to show how it works http://plnkr.co/edit/mLYIvoGHRkGxoOD4iJjU?p=preview 

But I'll close this since more generalized version is on it's way.

**Pull request closed without merging**
