### PR TITLE
Universal server side rendering

### PR DESCRIPTION
**Pull request by stupiduglyfool**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Any references to Window, Document, MouseEvent, KeyboardEvent cause errors.

https://github.com/swimlane/ngx-datatable/issues/173

**What is the new behavior?**
Similar to the comment here..
https://github.com/swimlane/ngx-datatable/issues/173#issuecomment-295388147

I've gone through all references and attempted to create a suitable workaround when the mentioned references are used.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Open to suggestions if anyone can suggest better approaches to my workarounds.

### CODE REVIEW

**Comment by amcdnl** [comment]
Doesn't typescript handle the `MouseEvent` and `KeyboardEvent` types automatically?

**Comment by stupiduglyfool** [comment]
If you look at the transpiled code 

https://github.com/swimlane/ngx-datatable/blob/master/release/index.js#L3809

There are dozens of mentions of MouseEvent and KeyboardEvent, all these are not defined.

**Comment by rsparrow** [comment]
What's the status on this PR? We are looking for the same change.

**Comment by amcdnl** [comment]
Merged.

**Comment by rsparrow** [comment]
@amcdnl humm... looks like the build had an issue, some sort of merge issue.

**Comment by rsparrow** [comment]
@stupiduglyfool This has now been merged into version 9.3.0 but on the universal side of things I'm still getting the following error:
```

/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:9038
var testStyle = document !== undefined ? document.createElement('div').style : undefined;
                ^

ReferenceError: document is not defined
    at Object../src/utils/prefixes.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:9038:17)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/utils/index.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:8812:10)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/components/datatable.component.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:5325:15)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/components/index.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:7307:10)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/datatable.module.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:7471:20)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)

/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:9038
var testStyle = document !== undefined ? document.createElement('div').style : undefined;
                ^

ReferenceError: document is not defined
    at Object../src/utils/prefixes.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:9038:17)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/utils/index.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:8812:10)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/components/datatable.component.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:5325:15)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/components/index.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:7307:10)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
    at Object../src/datatable.module.ts (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:7471:20)
    at __webpack_require__ (/usr/src/project/node_modules/@swimlane/ngx-datatable/release/index.js:35:30)
```

Any suggestions?

**Comment by rsparrow** [comment]
@stupiduglyfool and @amcdnl I've found a solution. I'll issue a bug and a pull request later today.

**Comment by mattma** [comment]
Using 9.3.0, still experience the same issue just like @rsparrow .

Using with @angular/service-worker

**Comment by compitDanielos** [comment]
@rsparrow I think all `document !== undefined` and `window !== undefined` whould to be changed to `typeof document !== 'undefined' ` and `typeof window !== 'undefined' `

**Comment by rsparrow** [comment]
@mattma My fixes didn't get packaged into a release until 9.3.1...

**Comment by mattma** [comment]
by updating to 9.3.1, it works as expected. Still waiting on `10.0.0` release for the **immutability** data. 

I am using `ngrx` and `ngrx-store-freeze` module. Due to the library modifying the original dataset with `$$`, I have to disable the `storeFreeze`. I believe @amcdnl will fix it by ``10.0.0` release. 

Is there a timeline on when the feature will drop? 

Thinking of switching to Angular CDK table module. i will be a quick bit of code refactor that I hope I can avoid with the future release of the library.

**Pull request merged**
