### PR TITLE
Fix issue when count is undefined

### PR DESCRIPTION
**Pull request by yociduo**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Throw exception

**What is the new behavior?**

Handle exception

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by yociduo** [comment]
#838 relate with the issue

**Comment by marjan-georgiev** [comment]
@yociduo thank you for the contribution. Could you revert the changes to the release folder please? Otherwise this looks good to me.

**Comment by yociduo** [comment]
@marjan-georgiev OK, reset those files

**Comment by marjan-georgiev** [comment]
Merged, thank you! 👍

**Pull request merged**
