### PR TITLE
Upgrade to angular 8

### LINKED ISSUE #1694: core-js 3.x
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

* **Table version:** 
14.0.0

* **Angular version:** 
7.2.15

Is there a plan to support core-js 3.1.2 ?
At now @swimlane/ngx-datatable@14.0.0 requires a peer of core-js@^2.5.0

### PR DESCRIPTION
**Pull request by marjan-georgiev**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

fixes #1694 
fixes: #1693

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by whyboris** [comment]
Can confirm:
- cloned the repository (clean copy)
- checked out `ng8` branch
- ran `npm install` (no errors)
- ran `npm start` -- was able to see the page with all the different types of datatable
- ran `npm test` -- `126 SUCCESS` (no failed, 3 skipped, 69.5% statement code coverage) 

🚀 🎉 🙌

**Comment by whyboris** [comment]
ps -- `npm install` gave this warning:
```
found 4 vulnerabilities (2 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Running `npm audit fix` resulted in:
```
fixed 0 of 4 vulnerabilities in 15965 scanned packages
  1 vulnerability required manual review and could not be updated
  2 package updates for 3 vulns involved breaking changes
```
Something to keep in mind for the future 👌

**Comment by marjan-georgiev** [comment]
@whyboris thanks for testing!

Merging. Will release 15.0.0 shortly.

**Comment by whyboris** [comment]
Thank you @marjan-georgiev -- I pulled in your release and our production app is now fully working with Angular 8 🎉 🙇 🤝 
Cheers!

**Comment by marjan-georgiev** [comment]
Great to hear!

**Comment by TidianeChelsea** [comment]
Thank You @marjan-georgiev 🎉 
All working GREAT.

**Comment by bleuscyther** [comment]
Nice!

**Comment by TidianeChelsea** [comment]
Hello @marjan-georgiev 

I just noticed that the **headerComponent** of **DatatableComponent** is always **_undefined_** for the new version. 

What may be the problem? 

Thanks.

**Pull request merged**
