### PR TITLE
Fix bug 459

### PR DESCRIPTION
**Pull request by gerhardboer**
**What kind of change does this PR introduce?** (check one with "x")
- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Cannot find file 'datatable.component.scss' and the AoT compilation fails.

**What is the new behavior?**
AoT compilation does not fail anymore

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No, but

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
It isn't pretty. I'm not sure why the relative path loading does not work. It might be an issue with a webpack loader or something.

I've tested before and after the change with an angular-cli app and an angular-class-starter app. Both had the same issue, and this kind of path loading fixes is.

### CODE REVIEW

**Comment by amcdnl** [comment]
You shouldn't have to reference the scss like that :S .... its assuming you have scss running in your stack.

I think a simple replace ( ugh ) might fix this in the build step.

**Comment by gerhardboer** [comment]
Yeah, i'm not happy about it either.

I actually expected the release version to NOT have any scss dependencies, or at least have the path of the styleUrls be wrapped in a webpack require, where the url it requires matches the one that it built.

It's the reason i tried this "solution", to make the path match more with the one it registers for the scss.

I don't have the webpack-knowledge to figure it out unfortunately.

**Comment by amcdnl** [comment]
This is actually ngc not webpack...

**Comment by gerhardboer** [comment]
Ah, well.. explains why nothing worked when i was fiddling with webpack.

Do you have a solution for this, or at least know where to look?

**Comment by amcdnl** [comment]
I temp fixed the issue, need to figure out better way tho.

**Pull request closed without merging**
