### PR TITLE
Fix compile error when using TemplateTypeCheck set to true

### PR DESCRIPTION
**Pull request by marcus13371337**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
1. Compilation error:
ERROR in node_modules/@swimlane/ngx-datatable/release/components/body/body-cell.component.d.ts.DataTableBodyCellComponent.html(17,11): : Expected 1 arguments, but got 0.

2. And onTreeAction in DataTableBodyCellComponent doesn't send the row

**What is the new behavior?**
1. No compilation error.
2. onTreeAction now sends the row

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by cmcclellen** [comment]
@amcdnl Any chance on getting this merged in soon and a release?  Cannot use this control under angular 6.1 currently with templatetypecheck.  Disabling templatetypecheck isn't really an option for many of us.

**Comment by ShinDarth** [comment]
Same problem here. This issue prevents me to upgrade to Angular 7.

@marjan-georgiev  @amcdnl can you please check this merge request?

**Comment by ShinDarth** [comment]
Same problem here.

@marjan-georgiev  @amcdnl can you please check this merge request?

**Comment by ShinDarth** [comment]
Same problem here.

@marjan-georgiev  @amcdnl can you please check this merge request?

**Comment by ShinDarth** [comment]
Same problem here.

@marjan-georgiev  @amcdnl can you please check this merge request?

**Comment by ShinDarth** [comment]
Same problem here.

@marjan-georgiev  @amcdnl can you please check this merge request?

**Comment by marjan-georgiev** [comment]
Merged, thanks!

**Comment by ShinDarth** [comment]
@marjan-georgiev @marcus13371337 thanks a lot, now it works

**Pull request merged**
