### PR TITLE
Issue #403: Column Alignment

### PR DESCRIPTION
**Pull request by imyque**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Issue #403 

**What is the new behavior?**
CSS classes can be applied to columns via the header-cell and body-cell components. The classes can be provided in the column definition as shown below;
this.columns = [
      { name: 'Id', prop: 'id'},
      { name: 'Name', prop: 'name' },
      { name: 'Email', prop: 'email', cssClasses:'demo demo1 demo2' }
    ];

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
I am very very new to Angular 2 and Typescript, so please don't laugh at my codes :-)
Secondly, how do I build and test this project locally?

### CODE REVIEW

**Comment by amcdnl** [comment]
Merged! Thanks!!!

**Comment by pixelsailor** [comment]
Is this available in 6.0.2? I don't see it documented and it appears to be breaking when I try to implement it. Getting a "known property" error so I'm guessing it's not in yet. Trying to use it within a template context if that makes a difference.
```
<ngx-datatable-column [cssClasses]="text-center"></ngx-datatable-column>
```

**Comment by rahulpathak** [comment]
Hi @amcdnl ,

How we can add **css class** in ngx-datatable-column ?
I'm using **Table version: 6.3.0**

**Comment by amcdnl** [comment]
Is there any issue why you can't use 7.x ?

**Comment by rahulpathak** [comment]
We can't upgrade angular 4 because we are working only angular 2. Is there other way to add class in ngx-datatable-column ?

**Comment by t-pankajkumar** [comment]
Hi,
I have been using "@swimlane/ngx-datatable": "11.1.7" version,
When im using [cssClasses] it is throwing errors

> Can't bind to 'cssClasses' since it isn't a known property of 'ngx-datatable-column'.

Please provide document link for this option.

Thank you.

**Comment by rahulpathak** [comment]
Hi @t-pankajkumar,

You have to use:
```
For header CSS:  **headerClass="className"** 
For column CSS :  **[cellClass]="className"**
```

**Comment by t-pankajkumar** [comment]
Hi @rahulpathak ,
I have tried as you mentioned but still no change.
btw im angular 5,
is there any setting i have to specify anywhere to enable this feature?

**Comment by zengchuan** [comment]
I have tried but still no change.
<ngx-datatable-column name="Test" prop="test" [flexGrow]="1" headerClass="textright" cellClass="textright">

**Comment by zengchuan** [comment]
I have the same problem. How to set text-align: right;
<ngx-datatable-column name="Test" prop="test" [flexGrow]="1" headerClass="textright" cellClass="textright">

**Comment by zengchuan** [comment]
<ngx-datatable
        class="material"
...
<ngx-datatable-column name="Test" [flexGrow]="1" prop="test" cellClass="zc-datatable-right"></ngx-datatable-column>

.ngx-datatable.material .datatable-body .datatable-body-row .datatable-body-cell.zc-datatable-right{
  text-align: right;
}

**Pull request merged**
