### PR TITLE
Footer position(Top/Bottom/Both) feature

### PR DESCRIPTION
**Pull request by madhuinwiter**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
There is one PR #751 for this.
Footer(Pagination with summary) display at the end of the table only.

**What is the new behavior?**
PR #751 will be solved.
Footer(Pagination with summary) display is now configurable with the following options for footerPosition input varaible
1.bottom 2. top 3. both

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by amcdnl** [comment]
So i grabbed your branch and made a few updates. https://github.com/swimlane/ngx-datatable/tree/madhuinwiter-footer-position-feature

I'm leaning towards going a step further by making the header totally customizable that way you could implement your own header and pager in there in whatever combination you like. Is this something you'd like to take on?

**Comment by madhuinwiter** [comment]
@amcdnl Exactly. Thank you.

**Comment by bertranddupraz** [comment]
Any chance to see this feature in an upcoming release? Thanks in advance

**Comment by a2345sooted** [comment]
Any updates on this being released?  I'd really like to use this table, but I must have paging at top of table.  I'm faced with decision of forking and adding feature myself or finding a different table.  Knowing status of this feature would really help when making that decision.

**Comment by dsimoes** [comment]
Hi.
After all this time this isn't merged and released. Is it ever going to be released?

Thanks.

**Comment by paulmartinjoy** [comment]
Hi, 
Is this feature already in the current version or is it still not released ?

**Pull request closed without merging**
