### PR TITLE
[selectAllRowsOnPage] is broken. #1725 : Bug Fix

### PR DESCRIPTION
**Pull request by sacgrover**
A check was missing in the code and after adding it everything working fine.

**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

https://github.com/swimlane/ngx-datatable/issues/1725
https://github.com/swimlane/ngx-datatable/issues/1817
https://github.com/swimlane/ngx-datatable/issues/1812

**What is the new behavior?**

Functionality is working as expected. 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by sacgrover** [comment]
@marjan-georgiev 

Could you please review this merge request?

**Comment by sbharam** [comment]
We are also facing same issue. Need this fix.
@marjan-georgiev  could you pls review & merge this PR. It would be helpful.

**Comment by sacgrover** [comment]
@marjan-georgiev Could you please check this request? If it doesn't look good to you then we can close it.

**Comment by sacgrover** [comment]
@Hypercubed

**Pull request merged**
