### PR TITLE
Fix issue #1465 relating to [groupRowsBy] property

### PR DESCRIPTION
**Pull request by JustAnotherSoftwareDeveloper**
…ties

**What kind of change does this PR introduce?** (check one with "x")
- [ X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-datatable/issues/1465

**What is the new behavior?**

The new behavior leverages existing functions to provide expected behavior. 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

I don't usually contribute to OSS, so I apologize if I'm going about this wrong.

### CODE REVIEW

**Comment by aijazkhan81** [comment]
Hey, did you find a solution for this?

**Comment by madmurdok** [comment]
@amcdnl Maybe you can merge it? It is essential for my project and I'd prefer to use main branch instead of fork version of ngx-datatables :)

**Comment by JustAnotherSoftwareDeveloper** [comment]
No response from developers. Closing

**Comment by federicogualdi** [comment]
any update on this issue?

**Comment by madmurdok** [comment]
@federicogualdi 
I forked ngx-datatable to my github and created fix by my own. Actually now I'm working with another project and another tech-stack... so I don't know, maybe this issue has been fixed in main branch to?...

**Pull request closed without merging**
