### PR TITLE
Fix issue with misaligned body content

### PR DESCRIPTION
**Pull request by stewx**
**What kind of change does this PR introduce?** (check one with "x")
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Misaligned body content in certain situations.

**What is the new behavior?**
Properly aligned body content.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
See issue #1319 for more info on defect.

### CODE REVIEW

**Comment by juristr** [comment]
Also here it seems as if they are not aligned at 1st load. 

image

http://swimlane.github.io/ngx-datatable/#row-details

Not sure whether that's related to this PR. Clicking the header re-aligns them automatically.

**Comment by stewx** [comment]
@juristr That is unrelated to this PR as far as I know, but it may have the same root cause.

**Comment by stewx** [comment]
@amcdnl Can you merge this?

**Comment by stefano-caporale-wk** [comment]
Please someone merge this. It's a very important fix. A proper datatable cannot have misaligned content.

**Comment by juristr** [comment]
@stewx ok, let's see whether once it's merged it'll also fix the one I reported. Otherwise I'll open another issue. Maybe @marjan-georgiev can merge this in?

**Comment by marjan-georgiev** [comment]
Merged, thank you! 👍

**Comment by juristr** [comment]
@marjan-georgiev thx a lot. Btw, do you happen to know what causes the misalignment I mentioned in this comment: https://github.com/swimlane/ngx-datatable/pull/1326#issuecomment-378278678 ?

Should I open another separate issue for that?

**Comment by babolinGiordano** [comment]
Hello,
I use version 11.2 and I still have the same problem, plus I don't understand if the bug is fixed or not.
I am Sorry for silly question

**Comment by stewx** [comment]
@babolinGiordano This was merged Apr 5, 2018 and 11.2.0 was released on Feb 20, 2018. This is merged but unreleased.

**Comment by babolinGiordano** [comment]
@stewx thank a lot, I wait for the release.

**Comment by masonwheeler** [comment]
Eagerly awaiting the release too.  I'm being affected by this bug and I'd love to see it go away.

**Comment by stewx** [comment]
@babolinGiordano There's  a new release as of 6 days ago

**Comment by gopal-g** [comment]
I am facing the issue mentioned in this [comment](https://github.com/swimlane/ngx-datatable/pull/1326#issuecomment-378278678) in v13.1.0 ... Any suggestions as to how to fix it ?

**Comment by stas-kh** [comment]
The same issue on my side

**Pull request merged**
