### PR TITLE
Added bootstrap theme

### PR DESCRIPTION
**Pull request by agil-NUBBA**
- Added bootstrap theme thx to  @Adondriel

**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

https://github.com/swimlane/ngx-datatable/issues/635

**What is the new behavior?**

The datatable now has a boostrap class for styling.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by wizarrc** [comment]
@agil-NUBBA I'm still kinda dumb when it comes to bootstrap styles and my question might seem dumb. How is this related to bootstrap exactly?

**Comment by agil-NUBBA** [comment]
well, I guess it isn't related to bootstrap, is just a style that makes the table look similar to a bootstrap table-striped, so in a BS page it looks a bit more "integrated" with the style.

**Comment by wizarrc** [comment]
@agil-NUBBA thanks for the clarification! I like the name, keep it.

**Comment by amcdnl** [comment]
Awesome! Thanks!

**Comment by Adondriel** [comment]
Glad you could use the stuff I posted for something awesome. :D

**Comment by amcdnl** [comment]
Can you PR a demo page? :)

**Pull request merged**
