### PR TITLE
#1793 Row-details - bug on the official example

### PR DESCRIPTION
**Pull request by sacgrover**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-datatable/issues/1793

**What is the new behavior?**
recalcLayout is conditioned in the case of set offset. It's working fine now and all test cases passed

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Thanks for great module. I am using ngx-datatable from last 3 years. I happy to contribute whenever I have time.

### CODE REVIEW

**Comment by sacgrover** [comment]
This one seems duplicate : https://github.com/swimlane/ngx-datatable/issues/1657

**Comment by dhairyashil** [comment]
@swimlanes,

Can you please review and merge this pull request?

**Comment by marjan-georgiev** [comment]
Thanks you!

**Comment by joernz** [comment]
hi @sacgrover @marjan-georgiev 
I'm still facing this bug with v17.1.0

when `[virtualization]` and `[scrollbarV]` are both `true`, then the `rowHeight` cannot be set to `'100%'` or `'auto'`, this will cause the disappearing of all rows below the expanded one.

```html
<ngx-datatable
            #mytable
            class="material expandable"
            [rows]="dnMotor.items"
            [virtualization]="true"
            [scrollbarV]="true"
            [rowHeight]="36"
            (page)="onPage($event)"
            (activate)="onActivate($event)"
            style="height: 750px;"
        >

        <ngx-datatable-row-detail [rowHeight]="'100%'" #myRowDetail (toggle)="onDetailToggle($event)">
```

I looked into this bugfix, but I think `recalcLayout()` will never be called when `[virtualization]` and `[scrollbarV]` are both true, right?

```js
if (!this.scrollbarV || (this.scrollbarV && !this.virtualization))
      this.recalcLayout();
```

please advise, many thanks

**Comment by btimfl** [comment]
Facing the same issue as @joernz mentioned. Any solution yet?

**Pull request merged**
