### PR TITLE
Add Datatable SubHeader

### PR DESCRIPTION
**Pull request by ktriek**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Header sorting issue when using custom template #681 

**What is the new behavior?**
Adds a sub header cell, Allows adding a description to column headers, column filtering ... 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by amcdnl** [comment]
Cool! Question for you: was there any reason why you didn't just use header templates to accomplish this?

**Comment by ktriek** [comment]
@amcdnl  Column sorting doesn't work currently when using header templates,
Also useful when the user wants to keep the default header and just add some details.

**Comment by amcdnl** [comment]
I think a better solution would be to fix the column sorting rather than implement a new header template type.

**Comment by dzfoxos** [comment]
This is very useful in my case, I just want to add column filtering so I don't think I should rewrite the whole header every time.

**Comment by amcdnl** [comment]
@ktriek - Thanks so much for your contribution. I think I'm going to close this PR in light of the approach I suggested. Its more generic and you can achieve the same results.

@dzfoxos - I understand thats a tad inconvenient but I think rather than add extra code, extra edge cases its the right approach for the tool.

thanks again for your contributions!!

**Pull request closed without merging**
