### PR TITLE
fix(resizeable): fix memory leak due to created element not cleaned up

### PR DESCRIPTION
**Pull request by macjohnny**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
a created dom not is not cleaned up correctly and thus a memory leak occurs, see https://github.com/angular/angular/issues/26954

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by macjohnny** [comment]
@marjan-georgiev could you please have a look at this one?

**Comment by Nikcharn** [comment]
Hi, @macjohnny. I checked this 2 functions:
1. this.renderer.destroyNode(this.resizeHandle) - memory leak fixed
2. this.renderer.removeChild(this.renderer.parentNode(this.resizeHandle), this.resizeHandle) - memory leaks remained

**Comment by macjohnny** [comment]
@Nikcharn are you sure? I tested it with both, development mode (`is.renderer.destroyNode(this.resizeHandle)` branch is taken) and with production mode (`is.renderer.removeChild(this.renderer.parentNode(this.resizeHandle), this.resizeHandle)` branch taken), and in both cases the memory leak is not present anymore

**Comment by macjohnny** [comment]
@Nikcharn how did you test it?
first branch can be tested with `ng serve`
the second branch can be tested with `ng serve --prod`

**Comment by Nikcharn** [comment]
@macjohnny, oh, sorry. I checked my terminal log and saw that I ran "ng serve" both times 😅

**Comment by marjan-georgiev** [comment]
LGTM 👍Thanks!

**Comment by spaceapplesoft** [comment]
@marjan-georgiev 

Hey! Do you think it would be possible to publish a new release to npm with this PR?

I'm working on a project which we're going to publish soon, and this PR has a fix that we need. ;)

**Pull request merged**
