### PR TITLE
Fix #1313 do not collapse row details when row updated

### LINKED ISSUE #1313: Update row column will collapse rowDetail
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Collapse rowDetail after column value updated

**Expected behavior**

Update column value without collapse rowDetail (or not refresh whole table)

**Reproduction of the problem**

like the example code below
https://stackblitz.com/edit/angular-yvwhus?file=app%2Fapp.component.ts

There is a button call "Austin growup" , after clicking , the Austin's age will change and update table through this.rows = [...this.rows] in function updateTable().

But when I click button after expanding the detail row, the table will refresh and collapse all the rowDetail.

I think the problem is this.rows = [...this.rows]. I believe that will refresh whole table.

so...is there any way to dynamically update one row's value without collapse rowDetail (or without whole table refresh).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 11.1.7

* **Angular version:** 5.1.1

* **Browser:** all

* **Language:**  TypeScript

### PR DESCRIPTION
**Pull request by therealjing**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#1313 

**What is the new behavior?**
Rows (including grouped rows) stay expanded when rows are updated, as row expansion now uses rowIdentity to keep track of whether a row is expanded or not.

**Does this PR introduce a breaking change?** (check one with "x")
- [x] Yes
- [ ] No

Previously, row expansion collapsed after a row was updated, this fix keeps expanded rows expanded after row updates.

Per comments in #1313, users may have kept track of the expanded rows themselves and toggled rowExpansion after a row change in order to keep the row expanded. This toggling caused the expanded row to flash (close and open again). After this fix, any additional toggle can/should be removed.

Impact on grouped rows: if grouped rows are set to expanded by default, the previous behaviour after a row change was for grouped rows to all be expanded again. After this fix, group row expansion will retain their previous state too.

Note: row expansion now uses rowIdentity to track whether a row is expanded or not, hence users of this functionality may need to provide a rowIdentity function.

**Other information**:

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
@therealjing can you revert the changes to the release folder please? Those files are generated only when we release.

**Comment by therealjing** [comment]
@marjan-georgiev sure, will do that in the next few days.

**Comment by therealjing** [comment]
@marjan-georgiev done, changes to release folder reverted.

**Comment by jgrenat** [comment]
Nice job @therealjing! We're facing the same problem in our project and are waiting for the merge to fix it. Is there anything we can do to help?

**Comment by Humberd** [comment]
This is the only issue we are facing. This needs to be merged

**Comment by Humberd** [comment]
How about this issue?

**Comment by Humberd** [comment]
We have published a forked package of this fix under https://www.npmjs.com/package/@acaisoft/ngx-datatable

**Comment by asultan001** [comment]
Guys any updates on whether or not this is planned to merge any time soon?

**Comment by onuraltun** [comment]
this solution worked for me. please merge this changes. i have to use two packages at same time

**Comment by rookuu** [comment]
@marjan-georgiev We're waiting on this change also. Can we get a status update?

**Comment by KingDarBoja** [comment]
In order to approve the merge, the conflicts must be resolved.

Also it requires some reviews from swimlane members in order to ensure the quality and proper behaviour of the library.

Just wait for it, there is a lot of issues being on the review queue and also other `ngx-*` libraries on top of that.

**Comment by ermarkar** [comment]
So when can we expect to get this merged?

**Comment by marjan-georgiev** [comment]
Looks good. I resolved the conflicts in https://github.com/swimlane/ngx-datatable/pull/1778, and merged it.

Thank you @therealjing and everyone else for the contribution!

**Pull request closed without merging**
