### PR TITLE
Column reorder

### PR DESCRIPTION
**Pull request by bergermanuel**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-datatable/issues/868

**What is the new behavior?**
new input for datatable wether columns should be swapped or not

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by amcdnl** [comment]
Can you resolve the conflicts?

**Comment by Matmo10** [comment]
@bergermanuel what's the status on this?

**Comment by bergermanuel** [comment]
@Matmo10 conflicts are solvedso it could be merged

**Comment by htrex** [comment]
Can this merge be released to the npm repo?

**Pull request merged**
