### PR TITLE
Add code to allow row details inside of row groups

### PR DESCRIPTION
**Pull request by marcushill**
**What kind of change does this PR introduce?** (check one with "x")
- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#1540 By request, I'm updating #1569 to master and it was easier at this point just to create a new branch.

**What is the new behavior?**
For row groups, each row inside of the group is now wrapped inside of an additional row-wrapper which allows us to display row details for each row. I have included a demo in this version (albeit mostly copy pasta from two other demos). At this point, I'm unable to grab a gif, but I'll try to do that tomorrow.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by Anthony-Jhoiro** [comment]
Is there any update about this feature ?

**Comment by Shaker1978** [comment]
Has this ever been released? In version 17.1.0 this feature is still not working...

**Comment by marcushill** [comment]
I submitted that patch years ago (using what little contribution guidelines I could find at the time). 

I no longer work on a team that consumes this control, but I believe they ended up working off a fork or using a different control due to lack of response on issues at the time.

**Comment by Shaker1978** [comment]
> 
> 
> I submitted that patch years ago (using what little contribution guidelines I could find at the time).
> 
> I no longer work on a team that consumes this control, but I believe they ended up working off a fork or using a different control due to lack of response on issues at the time.

Thanks for your reply and the patch. It's sad, that it hasn't been merged after the work you've done, understanding the code and changing it to make it work. Disappointing.

**Comment by Kristof-De-Bock** [comment]
Hi, will this feature be deployed? Or will it remain just a PR?

**Pull request closed without merging**
