### PR TITLE
Update for Angular 4.0.0

### PR DESCRIPTION
**Pull request by alanpurple**
This is for breaking changes in Angular 4.0.0

**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
for angular 2.4.x

**What is the new behavior?**
for angular 4.0.x

**Does this PR introduce a breaking change?** (check one with "x")
- [ x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
use 6.0.2 for angular 2.4.x

**Other information**:

### CODE REVIEW

**Comment by amcdnl** [comment]
I think I'd like to have this in a branch or something rather than on master until Angular4 is out. Thoughts?

**Comment by alanpurple** [comment]
@amcdnl  agreed, should be on additional branch

**Comment by Koslun** [comment]
With rc1 out recently, has someone already created a branch one could play around with? 

And is anyone anticipating the breaking changes of angular 4 to affect this library in some dramatic way? Or only minimal breaking changes expected/sen so far? I would suspect the latter but figure there could always be something minor that could cause a major head ache.

**Comment by amcdnl** [comment]
Yup, master is going to become 4.0 ... merged!

**Pull request merged**
